/****************************************************************************


resource.h

produced by Borland Resource Workshop


*****************************************************************************/
#ifndef DS_3DLOOK 
	#define DS_3DLOOK 0x0004L 
#endif

#define CM_KEY101	101
#define ABOUT_DLG	2
#define NULL_ICON	2
#define SOUNDP_DLG	1
#define SOUNDP_ICO	1
#define SOUNDP_MENU	1
#define IDM_CONTROL_PLAY	107
#define IDM_CONTROL_STOP	108
#define IDM_FILE_CLOSE	106
#define IDM_FILE_SAVEAS	105
#define IDM_FILE_SAVE	104
#define IDM_HELP_HELP	102
#define IDM_HELP_ABOUT	103
#define IDM_FILE_OPEN	101
